update
upgrade

tap homebrew/versions
tap phinze/homebrew-cask
tap gaishimo/homebrew-cask
install brew-cask

install zsh
install git
install coreutils
install samba

# ruby
install rbenv
install ruby-build
install rbenv-gemset
install rbenv-gem-rehash
install mysql

install gawk
install gnu-sed
install nmap
install wget
install tree
install jq

install imagemagick
install graphviz

install tmux
install openssl
install readline
install nkf
tap sanemat/font
install ricty
install cmake
install libtool
install automake
install hub
install redis
install watch
install ag
install ipcalc
install ctags

install docker
install boot2docker

install mecab
install mecab-ipadic

install reattach-to-user-namespace

install ffmpeg

# casks

cask install java
cask install firefox
cask install opera
cask install google-chrome
cask install google-japanese-ime
cask install sequel-pro
cask install atom
cask install skitch
cask install skype
cask install charles
cask install dash
cask install kobito
cask install virtualbox
cask install vagrant
cask install yorufukurou
cask install sophos-anti-virus-home-edition
cask install dropbox
cask install hipchat
cask install heroku-toolbelt
cask install alfred
cask install divvy
cask install macvim
cask install sublime-text3
cask install iterm2
cask install node-webkit
cask install jumpcut
cask install xquartz
cask install wireshark

cask alfred link

